### ISSUE TITLE
doubt here

### ISSUE THREAD

**Issue by juanjoayala01** [azael1337/discord-nitro-sniper#6]
the program runs so its fine at that point, but it only says im connected, nothing else. So, do i have to join any giveaway server or something? because im testing it in a full brand new acc so the account doesent have more than 1 server, its own.

**Comment by juanjoayala01** [comment]
oh, thank you in advance for your reply

**Comment by azael1337** [comment]
no probs sarcasm or not, heres a good server list, search by keyword and enter

https://disboard.org/
